// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityBreakdown } from "./QualityBreakdown";

export type Article = { id: bigint, title: string, url_slug: string, file: string, target_keyword: string | null, keyword_difficulty: string | null, target_volume: bigint, published_date: string | null, word_count: bigint, status: string, content_gaps_addressed: Array<string>, estimated_traffic_monthly: string | null, project_id: string, 
/**
 * Overall quality score 0-100
 */
quality_score: number | null, 
/**
 * Letter grade (A, B, C, D, F)
 */
quality_grade: string | null, 
/**
 * When quality was last rated (ISO 8601 string)
 */
quality_rated_at: string | null, 
/**
 * Whether article is ready to publish
 */
publishing_ready: boolean | null, 
/**
 * Category scores breakdown
 */
quality_breakdown: QualityBreakdown | null, };
