// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Article = { id: bigint, title: string, url_slug: string, file: string, target_keyword: string | null, keyword_difficulty: string | null, target_volume: bigint, published_date: string | null, word_count: bigint, status: string, content_gaps_addressed: Array<string>, estimated_traffic_monthly: string | null, project_id: string, };
