// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";

export type CalculatorRecommendation = { strategy: string, ticker_universe: string, priority_tickers: Array<string>, indexing_policy: string, reason: string, approval_status: ApprovalStatus, };
