// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CampaignStats = { total_posts: bigint, by_status: { [key in string]?: bigint }, by_platform: { [key in string]?: bigint }, };
