// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculatorRecommendation } from "./CalculatorRecommendation";
import type { HubRecommendation } from "./HubRecommendation";
import type { MergeRecommendation } from "./MergeRecommendation";
import type { StrategyRisk } from "./StrategyRisk";
import type { TerritoryRecommendation } from "./TerritoryRecommendation";

export type CannibalizationStrategy = { generated_at: string, merge_recommendations: Array<MergeRecommendation>, hub_recommendations: Array<HubRecommendation>, calculator_recommendations: Array<CalculatorRecommendation>, territory_recommendations: Array<TerritoryRecommendation>, risks: Array<StrategyRisk>, };
