// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single finding exposed over IPC.
 */
export type ClarityFindingPayload = { issue_type: string, severity: string, url: string, evidence: string, recommendation: string, clarity_dashboard_url: string, };
