// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Page score payload exposed over IPC.
 */
export type ClarityPageScorePayload = { url: string, total_sessions: number, rage_click_count: number, dead_click_count: number, quickback_count: number, excessive_scroll_count: number, error_click_count: number, script_error_count: number, avg_engagement_seconds: number, avg_scroll_depth: number, rage_click_rate: number, dead_click_rate: number, quickback_rate: number, z_score: number, clarity_dashboard_url: string, };
