// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorTopKeyword } from "./CompetitorTopKeyword";

/**
 * Competitor traffic insight for the final selection agent.
 */
export type CompetitorInsight = { domain: string, traffic_monthly_avg: number, top_keywords: Array<CompetitorTopKeyword>, };
