// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Competitor word count data.
 */
export type CompetitorWordCount = { url: string, domain: string, position: number, word_count: number, };
