// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A competitor top keyword from Ahrefs traffic data.
 */
export type CompetitorTopKeyword = { keyword: string, traffic: number | null, position: number | null, };
