// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Section of a competitor article.
 */
export type CompetitorSection = { heading: string, level: number, word_count: number, is_thin: boolean, };
