// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single validated follow-up proposal the user can select in the picker.
 */
export type ContentReviewProposal = { id: string, task_type: string, title: string, description: string | null, params: JsonValue, idempotency_key: string, priority: string | null, };
