// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single validated follow-up proposal the user can select in the picker.
 */
export type ContentReviewProposal = { 
/**
 * Stable selection id (e.g. `fix_content_article:{article_id}`).
 */
id: string, task_type: string, title: string, description?: string | null, 
/**
 * Spawn payload (article_id, article_title, article_file, url_slug,
 * target_keyword, suggestions, priority).
 */
params: JsonValue, idempotency_key: string, priority?: string | null, };
