// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentReviewProposal } from "./ContentReviewProposal";
import type { DroppedProposal } from "./DroppedProposal";

/**
 * Validated proposal list stored on the parent task after content_review.
 * Cap of 5 proposals is enforced by `engine::content_review_selection`.
 */
export type ContentReviewSelectableArtifact = { findings_summary?: string | null, proposals: Array<ContentReviewProposal>, dropped: Array<DroppedProposal>, 
/**
 * Source of the proposals: `"recommendations"` | `"investigation"` | etc.
 */
source: string, };
