// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewArticleRecommendation } from "./ReviewArticleRecommendation";

/**
 * Structured output from the content review recommendation agent.
 * Uses rig's Extractor<T> for type-safe generation via tool calling.
 */
export type ContentReviewRecommendations = { generated_at: string, total_articles: number, articles: Array<ReviewArticleRecommendation>, };
