// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentFixVerifiedItem = { category: string, status: string, detail: string | null, actual: string | null, expected: string | null, };
