// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentFixVerifiedItem } from "./ContentFixVerifiedItem";

export type ContentFixVerificationReport = { summary: string, verified_count: number, failed_count: number, skipped_count: number, fixes: Array<ContentFixVerifiedItem>, };
