// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionAddition } from "./SectionAddition";
import type { TransitionEdit } from "./TransitionEdit";

/**
 * A structured patch describing how to merge unique content from redirect
 * targets into a keeper article.
 */
export type ContentMergePatch = { 
/**
 * Absolute or repo-relative path to the keeper MDX file.
 */
keeper_file: string, 
/**
 * Sections to insert into the keeper.
 */
additions: Array<SectionAddition>, 
/**
 * Any prose transitions or edits to existing paragraphs.
 */
transitions: Array<TransitionEdit>, 
/**
 * Notes for the reviewer (not applied automatically).
 */
notes: Array<string>, };
