// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayConfig } from "./OverlayConfig";
import type { Platform } from "./Platform";
import type { PostFormat } from "./PostFormat";
import type { TemplateExample } from "./TemplateExample";

export type ContentTemplate = { id: string, project_id: string | null, name: string, description: string | null, platform: Platform, format: PostFormat, creation_prompt: string, overlay_config: OverlayConfig, default_hashtags: Array<string>, example_output: TemplateExample | null, created_at: string, updated_at: string, };
