// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Platform } from "./Platform";
import type { PostFormat } from "./PostFormat";

export type CreateTemplateRequest = { project_id: string | null, name: string, platform: Platform, format: PostFormat, description: string, };
