// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrRecommendation } from "./CtrRecommendation";

export type CtrAgentOutput = { recommendations: Array<CtrRecommendation>, };
