// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFixApplied } from "./CtrFixApplied";
import type { CtrFixSkipped } from "./CtrFixSkipped";

export type CtrFixReport = { applied: Array<CtrFixApplied>, skipped: Array<CtrFixSkipped>, summary: string, };
