// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFixCheckResult } from "./CtrFixCheckResult";

export type CtrFixVerificationReport = { article_id: bigint, file: string, overall_status: string, checks: Array<CtrFixCheckResult>, };
