// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFixPatchFaqQuestion } from "./CtrFixPatchFaqQuestion";
import type { CtrSnippetPatch } from "./CtrSnippetPatch";

export type CtrFixPatchChanges = { title: string | null, description: string | null, first_paragraph: string | null, faq_questions: Array<CtrFixPatchFaqQuestion> | null, snippet_patch: CtrSnippetPatch | null, };
