// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtrFixCheckResult = { check_type: string, status: string, expected: string, actual: string, detail: string | null, };
