// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFixPatchChanges } from "./CtrFixPatchChanges";

/**
 * The agent returns this instead of raw MDX. Rust applies it deterministically.
 */
export type CtrFixPatch = { article_id: bigint, file: string, error: string | null, changes: CtrFixPatchChanges, };
