// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFixType } from "./CtrFixType";

export type CtrFixChange = { fix_type: CtrFixType, old: string | null, new: string, };
