// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFix } from "./CtrFix";

export type CtrRecommendation = { article_id: bigint, url_slug: string, 
/**
 * Canonical file path for the article MDX file. Guaranteed by Rust context enrichment.
 */
file: string, priority: string | null, expected_ctr_improvement: string | null, 
/**
 * Target keyword for this article (used by verifier for snippet keyword check).
 * Guaranteed by Rust context enrichment.
 */
target_keyword: string, fixes: Array<CtrFix>, };
