// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrSnippetFormat } from "./CtrSnippetFormat";

export type CtrSnippetPatch = { target_query: string, format: CtrSnippetFormat, heading: string, answer_paragraph: string, ordered_list: Array<string> | null, comparison_table: Array<Array<string>> | null, };
