// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtrSnippetMarkup = { has_question_h2: boolean, has_ordered_list: boolean, has_table: boolean, };
