// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtrSnippetFormat = "direct_answer_paragraph" | "comparison_paragraph" | "best_list_ordered" | "comparison_table" | "definition_with_steps";
