// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtrTemplatePageDetail = { article_id: bigint, url: string, file: string, source_title: string, rendered_title: string, };
