// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrTemplatePageDetail } from "./CtrTemplatePageDetail";

/**
 * Result of detecting a repeated site-wide title template pattern.
 */
export type CtrTemplateDetectionResult = { 
/**
 * The detected template pattern, e.g. "{title} | Days to Expiry | Days to Expiry — Option Selling Analyzer"
 */
detected_pattern: string, 
/**
 * The desired corrected pattern, e.g. "{title} | Days to Expiry"
 */
desired_pattern: string, 
/**
 * Number of pages affected by this pattern
 */
affected_pages: number, 
/**
 * Candidate framework files that may contain the title template
 */
candidate_files: Array<string>, 
/**
 * Confidence level: "high", "medium", or "low"
 */
confidence: string, 
/**
 * Whether this fix requires manual review before applying
 */
requires_manual_review: boolean, 
/**
 * Sample URLs to verify after fix
 */
verification_urls: Array<string>, 
/**
 * Per-page details for affected articles
 */
pages: Array<CtrTemplatePageDetail>, };
