// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrVerifiedArticle } from "./CtrVerifiedArticle";

export type CtrVerificationReport = { summary: string, verified_count: number, failed_count: number, skipped_count: number, articles: Array<CtrVerifiedArticle>, };
