// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFixType } from "./CtrFixType";

export type CtrVerifiedFix = { fix_type: CtrFixType, status: string, 
/**
 * Human-readable failure detail: "title is 61 chars (max 55)", "meta is 132 chars (expected 140-155)", etc.
 */
detail: string | null, 
/**
 * Actual value that was measured
 */
actual: string | null, 
/**
 * Expected rule / threshold
 */
expected: string | null, };
