// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrVerifiedFix } from "./CtrVerifiedFix";

export type CtrVerifiedArticle = { article_id: bigint, file: string, status: string, fixes: Array<CtrVerifiedFix>, };
