// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verdict from the agentic distinctiveness review step.
 */
export type DistinctivenessVerdict = { target_url: string, verdict: string, confidence: string, recommendation: string, keep_url: string | null, redirect_url: string | null, reason: string, suggested_title: string | null, suggested_h1: string | null, };
