// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A raw proposal that failed validation, with the reason recorded for the UI.
 */
export type DroppedProposal = { reason: string, task_type: string | null, detail: string | null, };
