// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnqueueItem } from "./EnqueueItem";
import type { EnqueueMode } from "./EnqueueMode";

/**
 * Request to enqueue tasks.
 */
export type EnqueueRequest = { items: Array<EnqueueItem>, mode: EnqueueMode, };
