// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";

export type HubRecommendation = { topic: string, suggested_url: string, suggested_title: string, intent: string, source_pages: Array<bigint>, spoke_pages: Array<bigint>, outline: Array<string>, approval_status: ApprovalStatus, };
