// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClusterContext } from "./ClusterContext";
import type { LinkSourceCandidate } from "./LinkSourceCandidate";
import type { TargetArticleSummary } from "./TargetArticleSummary";
import type { TargetDiagnosis } from "./TargetDiagnosis";

/**
 * Per-target context built by `IhcBuildTargetContext`.
 */
export type IndexingTargetContext = { target: TargetArticleSummary, cluster: ClusterContext | null, diagnosis: TargetDiagnosis, source_candidates?: Array<LinkSourceCandidate>, };
