// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexingLinkTarget } from "./IndexingLinkTarget";

/**
 * Full `indexing_link_target` artifact document (`{ campaign_task_id, target }`).
 */
export type IndexingLinkTargetArtifact = { campaign_task_id?: string | null, target: IndexingLinkTarget, };
