// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DistinctivenessVerdict } from "./DistinctivenessVerdict";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Per-target plan produced by the reduce step.
 */
export type IndexingTargetPlan = { url: string, reason_code: string, recommended_action: string, context_artifact_key: string | null, distinctiveness_verdict: DistinctivenessVerdict | null, content_audit_summary: JsonValue | null, };
