// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexingCampaignSummary } from "./IndexingCampaignSummary";
import type { IndexingTargetPlan } from "./IndexingTargetPlan";

/**
 * The full campaign plan written by `ihc_reduce_plan`.
 */
export type IndexingCampaignPlan = { generated_at: string, targets: Array<IndexingTargetPlan>, summary: IndexingCampaignSummary, };
