// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsecutiveViolation } from "./ConsecutiveViolation";
import type { SectionPresence } from "./SectionPresence";

/**
 * Keyword density analysis report.
 */
export type KeywordDensityReport = { keyword: string, total_words: number, keyword_count: number, density_percent: number, is_stuffed: boolean, is_underused: boolean, section_distribution: Array<SectionPresence>, consecutive_violations: Array<ConsecutiveViolation>, };
