// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorInsight } from "./CompetitorInsight";
import type { ScoredKeyword } from "./ScoredKeyword";

/**
 * Output from Step 2: research_ahrefs_pipeline
 *
 * The deterministic step calls Ahrefs API for each theme,
 * deduplicates, fetches KD scores, and returns structured data.
 */
export type KeywordPipelineOutput = { 
/**
 * All keywords found with their scores
 */
keywords: Array<ScoredKeyword>, 
/**
 * The themes that were used for research
 */
themes: Array<string>, 
/**
 * Competitor domains extracted from the seed step
 */
competitors: Array<string>, 
/**
 * Competitor traffic insights for context
 */
competitor_insights: Array<CompetitorInsight>, 
/**
 * Total candidates before filtering
 */
total_candidates: number, 
/**
 * Number of keywords with full data (KD + volume)
 */
with_data_count: number, };
