// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSiteLinkProfile } from "./LiveSiteLinkProfile";

export type LiveSiteLinkScanResult = { total_pages: number, total_internal_links: number, pages_with_outgoing: number, pages_with_incoming: number, orphan_urls: Array<string>, profiles: Array<LiveSiteLinkProfile>, };
