// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSiteAuditSummary = { total_pages: number, healthy_pages: number, pages_with_issues: number, thin_content_pages: number, missing_metadata_pages: number, weak_heading_pages: number, stale_crawl_pages: number, weak_interlinking_pages: number, orphan_pages: number, };
