// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSiteGscSyncResult = { site_url: string, start_date: string, end_date: string, rows_fetched: number, pages_synced: number, pages_unmatched: number, synced_at: string, };
