// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preflight report for a merge operation.
 */
export type MergePreflightReport = { keeper_file_exists: boolean, keeper_is_indexable: boolean, redirect_files_exist: Array<string>, redirect_files_missing: Array<string>, redirect_cycles_detected: Array<string>, can_proceed: boolean, notes: Array<string>, };
