// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PageMetrics = { page: string, clicks: number, impressions: number, ctr: number, position: number, };
