// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrerequisiteCheck } from "./PrerequisiteCheck";

/**
 * Output of the `IhcCheckPrerequisites` step.
 */
export type PrerequisiteReport = { all_fresh: boolean, checks: Array<PrerequisiteCheck>, };
