// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: string, name: string, path: string, content_dir: string | null, site_url: string | null, site_id: string | null, active: boolean, agent_provider: string | null, };
