// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ProposedTask = { 
/**
 * Task type string from task_definitions (e.g. `ctr_audit`, `fix_content_article`).
 */
task_type: string, title: string, reason: string, 
/**
 * Opaque task params; empty object when not needed.
 */
params: JsonValue, };
