// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QualityCheck = { id: string, label: string, pass: boolean, detail?: string | null, };
