// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Category scores for quality breakdown
 */
export type QualityBreakdown = { 
/**
 * Content length and structure score
 */
content: number, 
/**
 * Keyword optimization score
 */
keywords: number, 
/**
 * Meta elements score
 */
meta_elements: number, 
/**
 * Content structure score
 */
structure: number, 
/**
 * Internal/external links score
 */
links: number, 
/**
 * Readability score
 */
readability: number, };
