// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueRunStatus } from "./QueueRunStatus";

/**
 * A durable queue run.
 */
export type QueueRun = { id: string, status: QueueRunStatus, pause_on_error: boolean, created_at: string, updated_at: string, started_at: string | null, finished_at: string | null, };
