// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of an existing fix task for a recommendation.
 */
export type RecommendationTaskStatus = { recommendation_type: string, recommendation_id: string, task_id: string | null, task_status: string | null, };
