// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecoveryStats = { total_attempts: number, linked: number, resolved: number, failed: number, total_links_added: number, };
