// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RedirectRecord = { url: string, last_crawled: string | null, redirect_type: string, issue: string, priority: number, suggested_action: string, final_url: string | null, };
