// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LandingPageCandidate } from "./LandingPageCandidate";
import type { SelectedKeyword } from "./SelectedKeyword";

/**
 * Output from Step 3: research_final_selection
 *
 * The LLM selects the best candidates from the structured data.
 */
export type ResearchFinalOutput = { 
/**
 * Selected informational keywords (for research_keywords task)
 */
results: Array<SelectedKeyword>, 
/**
 * Selected landing page candidates (for research_landing_pages task)
 */
landing_page_candidates: Array<LandingPageCandidate>, };
