// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewSuggestion = { category: string, current: string, proposed: string, reason: string, priority?: string | null, };
