// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractedExample } from "./ExtractedExample";
import type { ExtractedFaq } from "./ExtractedFaq";
import type { ExtractedHeading } from "./ExtractedHeading";
import type { ExtractedTable } from "./ExtractedTable";

/**
 * Extracted unique sections from a redirect page.
 */
export type SectionInventory = { file: string, headings: Array<ExtractedHeading>, tables: Array<ExtractedTable>, examples: Array<ExtractedExample>, faqs: Array<ExtractedFaq>, };
