// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from Step 1: research_seed_extraction
 * 
 * The LLM reads the project brief and extracts research themes and competitor domains.
 * Contract: MUST return valid JSON with {"themes": [...], "competitors": [...]}
 */
export type SeedExtractionOutput = { 
/**
 * 8-12 seed themes for Ahrefs keyword ideas API
 * Each theme should be 1-3 words maximum
 */
themes: Array<string>, 
/**
 * 2-3 competitor domains for traffic/context cross-reference
 */
competitors?: Array<string>, };
