// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidatedSeed } from "./ValidatedSeed";

/**
 * Output from Step 3: research_seed_validation
 *
 * The LLM filters autocomplete suggestions for domain relevance.
 * Contract: MUST return valid JSON with {"validated_seeds": [{"theme": ..., "seeds": [...]}]}
 */
export type SeedValidationOutput = { validated_seeds: Array<ValidatedSeed>, };
