// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidatedSeed } from "./ValidatedSeed";

/**
 * Output from the research_seed_validation step.
 *
 * The LLM validates extracted themes for domain relevance and proposes 1-3
 * seed phrasings per on-topic theme.
 * Contract: MUST return valid JSON with {"validated_seeds": [{"theme": ..., "seeds": [...]}]}
 */
export type SeedValidationOutput = { validated_seeds: Array<ValidatedSeed>, };
