// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSuggestion } from "./ReviewSuggestion";

/**
 * Single-article recommendations — used when processing one article at a time.
 */
export type SingleArticleRecommendations = { suggestions: Array<ReviewSuggestion>, };
