// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceConfig = { include_articles: boolean, article_slugs: Array<string>, include_screenshots: boolean, screenshot_dirs: Array<string>, include_specs: boolean, };
