// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StepProgress = { step_name: string, kind: string, status: string, message: string, output: string | null, };
