// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CannibalizationStrategy } from "./CannibalizationStrategy";
import type { StrategyReview } from "./StrategyReview";

/**
 * A strategy with per-recommendation approval state merged in.
 */
export type StrategyWithReviews = { strategy: CannibalizationStrategy, reviews: Array<StrategyReview>, strategy_id: string, project_id: string, };
