// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetDiagnosis = { has_links: boolean, is_long: boolean, has_cluster_siblings: boolean, suspected_root_cause: string, };
