// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPolicy } from "./AgentPolicy";
import type { ExecutionMode } from "./ExecutionMode";
import type { Priority } from "./Priority";
import type { TaskArtifact } from "./TaskArtifact";
import type { TaskRun } from "./TaskRun";
import type { TaskStatus } from "./TaskStatus";

export type Task = { id: string, type: string, phase: string, status: TaskStatus, priority: Priority, execution_mode: ExecutionMode, agent_policy: AgentPolicy, title: string | null, description: string | null, project_id: string, depends_on: Array<string>, artifacts: Array<TaskArtifact>, run: TaskRun, created_at: string, updated_at: string, };
