// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskRun = { attempts: number, last_error: string | null, provider: string | null, prompt_tokens: bigint | null, completion_tokens: bigint | null, };
