// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskArtifact = { key: string, path: string | null, artifact_type: string | null, source: string | null, content: string | null, };
