// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerritoryContentRec = { title: string, url_slug: string, intent: string, rationale: string, };
