// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";

export type TerritoryRecommendation = { theme: string, priority: string, demand_evidence: Array<string>, suggested_tasks: Array<string>, approval_status: ApprovalStatus, };
