// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validated seed within a theme.
 */
export type ValidatedSeed = { theme: string, seeds: Array<string>, };
