// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetType } from "./AssetType";

export type VisualAsset = { path: string, asset_type: AssetType, description: string, overlay_text: string | null, };
