// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityBreakdown } from "./QualityBreakdown";

export type Article = { id: bigint, title: string, url_slug: string, file: string, target_keyword: string | null, keyword_difficulty: string | null, target_volume: bigint, published_date: string | null, word_count: bigint, status: string, review_status: string | null, review_started_at: string | null, last_reviewed_at: string | null, review_count: bigint, content_gaps_addressed: Array<string>, estimated_traffic_monthly: string | null, project_id: string, 
/**
 * Overall quality score 0-100
 */
quality_score: number | null, 
/**
 * Letter grade (A, B, C, D, F)
 */
quality_grade: string | null, 
/**
 * When quality was last rated (ISO 8601 string)
 */
quality_rated_at: string | null, 
/**
 * Whether article is ready to publish
 */
publishing_ready: boolean | null, 
/**
 * Category scores breakdown
 */
quality_breakdown: QualityBreakdown | null, 
/**
 * Page type: "hub", "pillar", "spoke", "landing", etc.
 */
page_type: string | null, 
/**
 * Content hash (SHA-256 of body) for change detection
 */
content_hash: string | null, 
/**
 * When the article content was last modified (file mtime or fix apply)
 */
last_edited_at: string | null, };
