// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CannibalizationSelection = { recommendation_type: string, recommendation_id: string, };
