// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single exported row exposed over IPC.
 */
export type ClarityExportRowPayload = { clarity_date: string, dimension_set: string, metric_name: string, dimensions: { [key in string]: JsonValue }, values: { [key in string]: JsonValue }, };
