// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaritySkippedFinding } from "./ClaritySkippedFinding";
import type { Task } from "./Task";

/**
 * Result of creating follow-up tasks from selected Clarity findings.
 */
export type ClarityTaskCreationResult = { created_tasks: Array<Task>, skipped: Array<ClaritySkippedFinding>, };
