// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection status returned to the frontend.
 */
export type ClarityConnectionStatus = { connected: boolean, message: string, };
