// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClarityFindingPayload } from "./ClarityFindingPayload";
import type { ClarityPageScorePayload } from "./ClarityPageScorePayload";

/**
 * Summary payload exposed over IPC.
 */
export type ClaritySummaryPayload = { project_id: string, generated_at: string, days_analyzed: bigint, page_scores: Array<ClarityPageScorePayload>, top_findings: Array<ClarityFindingPayload>, };
