// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A finding that was skipped during follow-up task creation, with the reason.
 */
export type ClaritySkippedFinding = { issue_type: string, url: string, reason: string, };
