// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiblingArticle } from "./SiblingArticle";

export type ClusterContext = { cluster_id: string, theme: string, sibling_count: number, siblings: Array<SiblingArticle>, shared_headings: Array<string> | null, exact_keyword_dupe: boolean, };
