// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorSection } from "./CompetitorSection";

/**
 * Full structure analysis of a competitor page.
 */
export type CompetitorStructure = { url: string, domain: string, sections: Array<CompetitorSection>, total_word_count: number, };
