// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Consecutive keyword violation.
 */
export type ConsecutiveViolation = { sentence_start: number, sentence_count: number, };
