// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentFixChanges } from "./ContentFixChanges";

/**
 * The agent returns this instead of raw MDX. Rust applies it deterministically.
 */
export type ContentFixPatch = { article_id: bigint, file: string, error: string | null, changes: ContentFixChanges, };
