// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityCheck } from "./QualityCheck";

/**
 * Structured output from the article quality review agent.
 * Used by the review_article_quality task to gate articles before clustering/linking.
 */
export type ContentQualityReview = { overall_pass: boolean, usefulness_score: bigint, image_score: bigint, seo_score: bigint, cluster_fit_score: bigint, signal_score: number | null, checks: Array<QualityCheck>, summary?: string | null, };
