// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtrFixType = "title_rewrite" | "meta_description" | "faq_schema" | "snippet_bait";
