// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFixChange } from "./CtrFixChange";

export type CtrFixApplied = { article_id: bigint, file: string, changes: Array<CtrFixChange>, };
