// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFixType } from "./CtrFixType";
import type { JsonValue } from "./serde_json/JsonValue";

export type CtrFix = { type: CtrFixType, current: string | null, 
/**
 * Recommended fix value. String for title/meta/snippet; array of questions for FAQ.
 */
recommended: JsonValue, reason: string | null, };
