// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrHealthArticle } from "./CtrHealthArticle";

export type CtrHealthSummary = { total_articles: number, healthy_count: number, unhealthy_count: number, improved_count: number, already_healthy_count: number, regressed_count: number, missing_files: number, title_issues: number, meta_issues: number, snippet_issues: number, faq_issues: number, last_audit_at: string | null, articles: Array<CtrHealthArticle>, pending_fix_tasks: number, completed_audits: number, open_issues_count: number, };
