// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtrHealthArticle = { id: bigint, title: string, url_slug: string, file: string, healthy: boolean, audit_status: string, issues: Array<string>, last_audited_at: string | null, last_audit_issues: Array<string>, resolved_issues: Array<string>, };
