// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrSnippetMarkup } from "./CtrSnippetMarkup";

export type CtrRenderedPageAudit = { article_id: bigint, url: string, file: string, source_title: string, rendered_title: string, rendered_title_length: number, title_issue_source: string, source_description: string, rendered_description: string | null, canonical_url: string | null, rendered_h1: string | null, schema_types: Array<string>, has_rendered_faq_page: boolean, rendered_faq_question_count: number, snippet_markup: CtrSnippetMarkup, issues: Array<string>, checked_at: string, };
