// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtrFix } from "./CtrFix";

export type CtrRecommendation = { article_id: bigint, url_slug: string, file: string | null, priority: string | null, expected_ctr_improvement: string | null, 
/**
 * Target keyword for this article (used by verifier for snippet keyword check).
 */
target_keyword: string | null, fixes: Array<CtrFix>, };
