// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DriftUrl = { url: string, slug: string, reason_code: string | null, verdict: string | null, 
/**
 * Sitemap `<lastmod>` value when available.
 */
lastmod: string | null, 
/**
 * Whether a matching MDX content file exists for this URL.
 */
has_content_file: boolean, 
/**
 * Frontmatter or structural issues that may prevent indexing (e.g. "noindex", "missing meta description").
 */
issues?: Array<string>, };
