// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DriftUrl = { url: string, slug: string, reason_code: string | null, verdict: string | null, };
