// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single task to enqueue.
 */
export type EnqueueItem = { task_id: string, project_id: string, title: string | null, task_type: string | null, project_name: string | null, };
