// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowUpTask } from "./FollowUpTask";
import type { StepProgress } from "./StepProgress";

export type ExecutionResult = { task_id: string, success: boolean, message: string, steps: Array<StepProgress>, follow_up_tasks: Array<FollowUpTask>, started_at: string, finished_at: string, };
