// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractedExample = { caption: string | null, code: string, language: string | null, };
