// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Finding = { title: string, description: string, 
/**
 * Tool-backed evidence supporting this finding.
 */
evidence: string, 
/**
 * `critical` | `warning` | `info`
 */
severity: string, 
/**
 * `auto_fixable` | `developer_actionable` | `hybrid` | `informational`
 */
fix_type: string, };
