// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FollowUpTask = { id: string, task_type: string, title: string, status: string, run_policy: string, review_surface: string, follow_up_policy: string, priority: string, };
