// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FollowUpTask = { id: string, task_type: string, title: string, status: string, execution_mode: string, priority: string, };
