// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GscAuthStatus = { service_account_configured: boolean, oauth_configured: boolean, authenticated: boolean, method: string | null, sa_path: string | null, oauth_path: string | null, };
