// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkSourceCandidate } from "./LinkSourceCandidate";

/**
 * Target payload inside the `indexing_link_target` task artifact.
 *
 * Shape fields are stable across IHC children, GSC recovery, and operator slug spawn.
 */
export type IndexingLinkTarget = { url: string, slug: string, article_id: bigint, file: string, reason_code: string, incoming_link_count_before: number, target_keyword: string, source_candidates: Array<LinkSourceCandidate>, };
