// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexingCampaignSummary = { total_targets: number, fix_content: number, add_links: number, merge: number, rewrite_title_h1: number, no_action: number, };
