// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InspectionRecord = { url: string, verdict: string | null, coverage_state: string | null, indexing_state: string | null, robots_txt_state: string | null, page_fetch_state: string | null, crawl_allowed: boolean | null, indexing_allowed: boolean | null, last_crawl_time: string | null, google_canonical: string | null, user_canonical: string | null, sitemaps: Array<string>, reason_code: string | null, action: string | null, priority: number, };
