// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search intent classification for a keyword.
 */
export type IntentClassification = { keyword: string, intent: string, confidence: number | null, };
