// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { ProposedTask } from "./ProposedTask";

/**
 * Typed output from the content_review investigate step when the backend
 * supports tool calling. Stored as the `investigation_findings` artifact.
 * Does **not** write `recommendations.json` (so fix_content_article spawning
 * no-ops safely until a later issue wires proposed_tasks).
 */
export type InvestigationFindings = { 
/**
 * 1–2 sentence TL;DR of the investigation.
 */
summary: string, findings: Array<Finding>, 
/**
 * Suggested downstream tasks (not validated or spawned by this step).
 */
proposed_tasks: Array<ProposedTask>, };
