// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectedKeyword } from "./SelectedKeyword";
import type { ValidatedSeed } from "./ValidatedSeed";

/**
 * Unified output for the complete keyword research workflow.
 *
 * Combines the outputs from all research steps:
 * - themes from seed extraction
 * - validated_seeds from seed validation
 * - selections from final selection
 *
 * This is the spec-target type for the `research_keywords` workflow.
 */
export type KeywordResearchOutput = { themes: Array<string>, validated_seeds: Array<ValidatedSeed>, selections: Array<SelectedKeyword>, };
