// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A landing page candidate (for commercial research)
 */
export type LandingPageCandidate = { 
/**
 * The keyword phrase
 */
keyword: string, 
/**
 * Monthly search volume
 */
estimated_volume: bigint, 
/**
 * Keyword difficulty score 0-100
 */
estimated_kd: bigint, 
/**
 * Search intent (transactional/commercial)
 */
intent: string, 
/**
 * Type of landing page
 */
landing_page_type: string, 
/**
 * Opportunity score (high/medium/low), derived from the commercial-value
 * ranking (volume × CPC) relative to the other selected candidates
 */
opportunity_score: string, 
/**
 * Why this keyword deserves a landing page
 */
opportunity_reason: string, 
/**
 * Suggested landing page title
 */
proposed_title: string, 
/**
 * Cost per click in USD (DataForSEO); `None` when the provider does not
 * return CPC
 */
cpc: number | null, 
/**
 * Winnability bucket: "target" | "differentiate" | "avoid"
 */
winnability: string | null, 
/**
 * Human-readable reason for the winnability score
 */
winnability_reason: string | null, };
