// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A potential source article for adding internal links.
 */
export type LinkSourceCandidate = { article_id: bigint, slug: string, title: string, file: string, reason: string, };
