// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSiteAuditPage } from "./LiveSiteAuditPage";
import type { LiveSiteAuditSummary } from "./LiveSiteAuditSummary";

export type LiveSiteAuditReport = { summary: LiveSiteAuditSummary, pages: Array<LiveSiteAuditPage>, };
