// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSitePage = { url: string, path: string, title: string, meta_description: string | null, h1: string | null, content_excerpt: string | null, word_count: bigint, heading_count: bigint, internal_links_out: bigint, status_code: bigint | null, gsc_clicks: number | null, gsc_impressions: number | null, gsc_ctr: number | null, gsc_position: number | null, gsc_synced_at: string | null, last_crawled_at: string, };
