// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSiteImportResult = { sitemap_url: string, discovered_urls: number, pages_imported: number, links_imported: number, pages_failed: number, };
