// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSiteAuditPage = { url: string, path: string, title: string, word_count: bigint, heading_count: bigint, internal_links_out: bigint, internal_links_in: bigint, has_meta_description: boolean, has_h1: boolean, last_crawled_at: string, crawl_age_days: bigint, issue_flags: Array<string>, issue_count: bigint, };
