// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSiteLinkProfile = { url: string, path: string, title: string, outgoing_urls: Array<string>, incoming_urls: Array<string>, unresolved_links: Array<string>, };
