// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validation report after merge apply.
 */
export type MergeValidationReport = { keeper_valid: boolean, keeper_word_count: number, redirect_map_path: string | null, issues: Array<string>, };
