// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";
import type { Confidence } from "./Confidence";

export type MergeRecommendation = { cluster_id: string, confidence: Confidence, keep_url: string, redirect_urls: Array<string>, merge_before_redirect: boolean, merge_instructions: Array<string>, reason: string, approval_status: ApprovalStatus, };
