// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoverMetrics = { key: string, current_clicks: number, current_impressions: number, current_position: number, previous_clicks: number, previous_impressions: number, previous_position: number, clicks_delta: number, impressions_delta: number, position_delta: number, };
