// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Multi-factor opportunity score for a keyword.
 */
export type OpportunityScore = { keyword: string, total_score: number, tier: string, factor_scores: { [key in string]: number }, };
