// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasSize } from "./CanvasSize";
import type { TextPosition } from "./TextPosition";

export type OverlayConfig = { canvas_size: CanvasSize, font_family: string, primary_color: string, secondary_color: string, text_position: TextPosition, max_text_length: number, };
