// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Platform = "tiktok" | "instagram_feed" | "instagram_reel" | "instagram_story";
