// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a single prerequisite freshness check.
 */
export type PrerequisiteCheck = { artifact: string, fresh: boolean, age_hours: bigint | null, action: string | null, };
