// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectMode } from "./ProjectMode";

export type ProjectCreate = { name: string, path: string | null, content_dir: string | null, site_url: string | null, site_id: string | null, sitemap_url: string | null, project_mode: ProjectMode, };
