// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of an individual item within a queue run.
 */
export type QueueItemStatus = "pending" | "running" | "completed" | "failed" | "skipped";
