// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueItemStatus } from "./QueueItemStatus";

/**
 * An item within a queue run.
 */
export type QueueItem = { run_id: string, position: bigint, task_id: string, project_id: string, status: QueueItemStatus, error: string | null, result_json: string | null, created_at: string, updated_at: string, title: string | null, task_type: string | null, project_name: string | null, };
