// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueItem } from "./QueueItem";
import type { QueueRun } from "./QueueRun";

/**
 * Full snapshot of the active queue for the frontend.
 */
export type QueueSnapshot = { run: QueueRun | null, items: Array<QueueItem>, };
