// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Readability analysis report for an article.
 */
export type ReadabilityReport = { flesch_reading_ease: number, flesch_kincaid_grade: number, smog_index: number, coleman_liau_index: number, automated_readability_index: number, passive_voice_percentage: number, sentence_variety_score: number, avg_sentence_length: number, cliche_count: number, filter_word_percentage: number, };
