// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RedditStats = { total_opportunities: bigint, by_status: { [key in string]?: bigint }, pending_by_severity: { [key in string]?: bigint }, average_score: number, max_score: number, };
