// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResearchShortlistEntry = { id: bigint | null, project_id: string, theme: string, seeds: Array<string>, source: string, status: string, priority: string, article_count: bigint | null, total_impressions: number | null, added_at: string, researched_at: string | null, covered_at: string | null, };
