// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResubmitCandidate = { url: string, slug: string, reason_code: string, priority_score: number, priority_reason: string, has_internal_links: boolean, incoming_link_count: number, gsc_impressions: number | null, target_keyword: string | null, published_date: string | null, };
