// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSuggestion } from "./ReviewSuggestion";

export type ReviewArticleRecommendation = { article_id: bigint, article_title: string, article_file: string, url_slug: string, target_keyword: string | null, suggestions: Array<ReviewSuggestion>, };
