// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleStrategy } from "./ScheduleStrategy";

export type ScheduleConfig = { strategy: ScheduleStrategy, start_at: string | null, interval_hours: number | null, };
