// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A scored keyword from the Ahrefs pipeline
 */
export type ScoredKeyword = { 
/**
 * The keyword phrase
 */
keyword: string, 
/**
 * Monthly search volume (if available)
 */
volume: bigint | null, 
/**
 * Keyword difficulty score 0-100 (if available)
 */
kd: number | null, 
/**
 * Search intent classification (if available)
 */
intent: string | null, 
/**
 * Top-ranking page traffic estimate
 */
traffic: number | null, 
/**
 * Whether we have complete data for this keyword
 */
has_data: boolean | null, 
/**
 * Search intent confidence score 0-100
 */
intent_confidence: number | null, 
/**
 * Coverage-gap score 0-100 from the coverage filter (higher = fills a
 * thinner cluster); `None` when no coverage analysis was available
 */
gap_score: number | null, };
