// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A section to add to the keeper.
 */
export type SectionAddition = { 
/**
 * Heading text (without # prefix).
 */
heading: string, 
/**
 * Body markdown content under the heading.
 */
content: string, 
/**
 * Where to insert: "after:<heading>", "before:<heading>", or "end".
 */
position: string, 
/**
 * Which source redirect page this content came from.
 */
source_file: string, };
