// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Section presence for keyword distribution.
 */
export type SectionPresence = { section: string, present: boolean, count: number, };
