// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selected keyword candidate for final output
 */
export type SelectedKeyword = { 
/**
 * The keyword phrase
 */
keyword: string, 
/**
 * Monthly search volume
 */
volume: bigint, 
/**
 * Keyword difficulty score 0-100
 */
difficulty: bigint, 
/**
 * Why this keyword was selected
 */
selection_reason: string, 
/**
 * Recommended article title
 */
recommended_title: string, };
