// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selected keyword candidate for final output
 */
export type SelectedKeyword = { 
/**
 * The keyword phrase
 */
keyword: string, 
/**
 * Monthly search volume
 */
volume: bigint, 
/**
 * Keyword difficulty score 0-100
 */
difficulty: bigint, 
/**
 * Top-ranking page traffic estimate
 */
traffic: bigint | null, 
/**
 * Why this keyword was selected
 */
selection_reason: string, 
/**
 * Recommended article title
 */
recommended_title: string, 
/**
 * Search intent classification (informational/commercial/transactional)
 */
intent: string | null, 
/**
 * Winnability bucket: "target" | "differentiate" | "avoid"
 */
winnability: string | null, 
/**
 * Human-readable reason for the winnability score
 */
winnability_reason: string | null, };
