// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CampaignStatus } from "./CampaignStatus";
import type { Platform } from "./Platform";
import type { SourceConfig } from "./SourceConfig";

export type SocialCampaign = { id: string, project_id: string, name: string, description: string | null, source_config: SourceConfig, target_platforms: Array<Platform>, template_ids: Array<string>, status: CampaignStatus, post_count: number, created_at: string, updated_at: string, };
