// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Platform } from "./Platform";
import type { PostFormat } from "./PostFormat";
import type { PostMetrics } from "./PostMetrics";
import type { PostStatus } from "./PostStatus";
import type { SourceType } from "./SourceType";
import type { VisualAsset } from "./VisualAsset";

export type SocialPost = { id: string, campaign_id: string, project_id: string, source_type: SourceType, source_id: string, source_url: string | null, platform: Platform, format: PostFormat, hook: string, caption: string, hashtags: Array<string>, cta: string, visual_assets: Array<VisualAsset>, 
/**
 * AI-generated prompt for external image generation (Midjourney, DALL-E, etc.)
 * This is generated by the agent during post creation and can be used
 * to create the visual asset that will have text overlaid.
 */
image_generation_prompt: string | null, status: PostStatus, scheduled_at: string | null, posted_at: string | null, platform_post_id: string | null, platform_post_url: string | null, metrics: PostMetrics | null, template_id: string, generated_by: string | null, generation_prompt_hash: string | null, created_at: string, updated_at: string, };
