// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";

export type StrategyReview = { id: bigint, strategy_id: string, project_id: string, recommendation_type: string, recommendation_id: string, approval_status: ApprovalStatus, approved_by: string | null, approved_at: string | null, notes: string | null, created_at: string, updated_at: string, };
