// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Raw Reddit post returned from the search API (before agent scoring).
 */
export type SubmissionSummary = { post_id: string, title: string | null, url: string | null, subreddit: string | null, author: string | null, upvotes: bigint | null, comment_count: bigint | null, created_at: string | null, days_old: bigint | null, selftext: string | null, };
