// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetArticleSummary = { url: string, slug: string, reason_code: string, title: string, h1: string, target_keyword: string, word_count: number, incoming_links: number, content_audit_health: string, article_id: bigint, file: string, };
