// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskReviewSurface = "none" | "keyword_picker" | "reddit_picker" | "cannibalization_picker" | "follow_up_tasks" | "artifact_review";
