// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerritoryContentRec } from "./TerritoryContentRec";
import type { TerritoryCoverageItem } from "./TerritoryCoverageItem";

export type TerritoryStrategy = { theme: string, priority: string, target_keywords: Array<string>, competitor_gaps: Array<string>, content_recommendations: Array<TerritoryContentRec>, existing_coverage: Array<TerritoryCoverageItem>, };
