// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerritoryCoverageItem = { article_id: bigint, title: string, url_slug: string, overlap: string, };
