// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transition edit to an existing paragraph.
 */
export type TransitionEdit = { 
/**
 * Existing text to locate (must be unique enough to find).
 */
find: string, 
/**
 * Replacement text.
 */
replace: string, };
