// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorWordCount } from "./CompetitorWordCount";

/**
 * Word count comparison result.
 */
export type WordCountComparison = { keyword: string, competitors: Array<CompetitorWordCount>, median: number, p75: number, recommended_min: number, user_word_count: number | null, gap: bigint | null, };
