#!/bin/bash
# Sync TypeScript bindings from Rust to frontend
# Usage: ./scripts/sync-bindings.sh

set -e

echo "🔄 Syncing TypeScript bindings from Rust to frontend..."

# Run the export tests to generate bindings
cd src-tauri
cargo test export_bindings --lib --quiet 2>/dev/null || true

# Copy generated bindings to frontend
mkdir -p ../src/lib/bindings
if [ -d "bindings" ]; then
    cp bindings/*.ts ../src/lib/bindings/
    # Also copy any subdirectories (e.g. serde_json/)
    for dir in bindings/*/; do
        if [ -d "$dir" ]; then
            base=$(basename "$dir")
            cp -r "$dir" ../src/lib/bindings/"$base"
        fi
    done
    echo "✅ Copied $(ls bindings/*.ts 2>/dev/null | wc -l) binding files"
else
    echo "⚠️  No bindings directory found. Running tests may have failed."
    exit 1
fi

# Regenerate the index.ts
cd ../src/lib/bindings

cat > index.ts << 'EOF'
// Auto-generated TypeScript bindings from Rust
// Generated by ts-rs - DO NOT EDIT MANUALLY
// Run `./scripts/sync-bindings.sh` to regenerate

EOF

# Generate export statements for each file
for file in *.ts; do
    if [ "$file" != "index.ts" ]; then
        name="${file%.ts}"
        echo "export type { $name } from './$name'" >> index.ts
    fi
done

echo "✅ Regenerated index.ts with $(grep -c "export type" index.ts) exports"
echo "🎉 Bindings sync complete!"
