#!/usr/bin/env bash
# Sync TypeScript bindings from Rust to frontend
# Usage: ./scripts/sync-bindings.sh

set -euo pipefail

cd "$(dirname "$0")/.."

echo "🔄 Syncing TypeScript bindings from Rust to frontend..."

# Run the export tests to generate bindings
cd src-tauri
cargo test export_bindings --lib --quiet
cd ..

# Wipe and recreate the destination directory so removed exports disappear
rm -rf src/lib/bindings
mkdir -p src/lib/bindings

# Copy generated bindings to frontend
if [ -d "src-tauri/bindings" ]; then
    cp src-tauri/bindings/*.ts src/lib/bindings/
    # Also copy any subdirectories (e.g. serde_json/)
    for dir in src-tauri/bindings/*/; do
        if [ -d "$dir" ]; then
            base=$(basename "$dir")
            cp -r "$dir" "src/lib/bindings/$base"
        fi
    done
    count=$(find src/lib/bindings -name '*.ts' -not -name 'index.ts' | wc -l | tr -d ' ')
    echo "✅ Copied $count binding file(s)"
else
    echo "❌ No bindings directory found. Running tests may have failed."
    exit 1
fi

# Regenerate the index.ts
cd src/lib/bindings

{
  echo "// Auto-generated TypeScript bindings from Rust"
  echo "// Generated by ts-rs - DO NOT EDIT MANUALLY"
  echo "// Run ./scripts/sync-bindings.sh to regenerate"
  echo
  for file in *.ts; do
    if [[ "$file" != "index.ts" ]]; then
      name="${file%.ts}"
      echo "export type { $name } from './$name'"
    fi
  done
} > index.ts

echo "✅ Regenerated index.ts with $(grep -c "export type" index.ts) exports"
echo "🎉 Bindings sync complete!"
